# Change these first
owner: BSGalvan # Your GitHub organization or username, where this repository lives
repo: freeDictionaryAPI-uptime # The name of this repository

sites:
  - name: Free Dictionary API Landing Page
    url: https://dictionaryapi.dev
  - name: GET to API Endpoint
    url: https://api.dictionaryapi.dev/api/v2/entries/en/hello
    method: GET

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /freeDictionaryAPI-uptime
  logoUrl: https://dictionaryapi.dev/favicon.ico
  name: Upptime
  introTitle: "**FreeDictionaryAPI** is a free and open-source dictionary API."
  introMessage: Our mission is to provide users with an API that they can use to build a game, learning application, or next-generation speech and text technology. This status page uses **real-time** data from our [GitHub repository](https://github.com/BSGalvan/freeDictionaryAPI-uptime). No server required — just GitHub Actions, Issues, and Pages. Get your own _for free_ [here](https://github.com/upptime/upptime).
  navbar:
    - title: Main Page
      href: https://dictionaryapi.dev
    - title: FD-API GitHub
      href: https://github.com/meetDeveloper/freeDictionaryAPI

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
